### ISSUE TITLE
I am getting error message as "exception error: Logon failure: unknown user name or bad password."

### ISSUE THREAD

**Issue by kheravarun08** [bodaghialib4/react-native-smb#2]
I have created SMB share on Mac machine which I am able to access using SMB through Android App 'AndSMB'. I am trying to access using this library and getting error :
exception error: Logon failure: unknown user name or bad password.

The user name and password are correct. Kindly let me know if I need to make any more changes.

**Comment by bodaghialib4** [comment]
Thanks for your issue.
I run the library in your test condition and got your error too.
For connecting to the SMB server I used the JCIFS java library. but after your issue, I realized that this library only supports SMB1. 
This error happened because macOS use SMB2.
I will replace the JCIFS library with a better library(which supports SMB2) as soon as possible.

**Comment by kheravarun08** [comment]
Thanks for the reply and support.
The library is a great help .
It would be great if it is compatible with both SMB2 and SMB3 as latest MacOS Catalina includes only SMB3..

**Comment by kheravarun08** [comment]
Hi,
We have to integrate SMB for one of our critical project .
It would be great if you could integrate it soon as it will help us to expedite our development.

**Comment by bodaghialib4** [comment]
Hi,
I am working on it.
I chose smbj library which support SMB2 & SMB3 and implemented these functionalities:

- connect
- list
- download
- upload
- rename file
- rename folder

I will make you aware as soon as the new version becomes ready.

**Comment by bodaghialib4** [comment]
Hi @kheravarun08,
the new version (0.2.0) is released.

**Comment by kheravarun08** [comment]
Thanks a lot......IT is working perfectly....
